# Screen constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# GFX constants
GFX_SCREEN_BACKGROUND_COLOR = (16, 32, 64)
GFX_PLAYER_COLOR = (255, 255, 255)
GFX_PLAYER_LINE_WEIGHT = 2

# Asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player constants
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300